### ISSUE TITLE
error in AppDelegate.swift

### ISSUE THREAD

**Issue by chulster** [mix1009/FlutterDropbox#5]
I'm trying to create an app that uses your Flutter Dropbox client. Following your instructions, I have edited AppDelegate.swift as follows:

```
import UIKit
import Flutter
import ObjectiveDropboxOfficial

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ app: UIApplication,
    open url: URL, 
    options: [UIApplication.OpenURLOptionsKey : Any] = [:]
  ) -> Bool {
    if let authResult = DBClientsManager.handleRedirectURL(url) {
      if authResult.isSuccess() {
        print("dropbox auth success")
      } else if (authResult.isCancel()) {
        print("dropbox auth cancel")
      } else if (authResult.isError()) {
        print("dropbox auth error \(authResult.errorDescription)")
      }
    }
    return true;
  }
}
```

(There was already an `override func application` statement in the original file, which I replaced with the one shown above.)

When trying to run the app, there is a build failure:

```
    2020-09-22 17:37:13.727 xcodebuild[77636:2499086]  DTDeviceKit: deviceType from 4c575fb44229a557d91773f8091e98bed27bccb3 was NULL
    2020-09-22 17:37:13.728 xcodebuild[77636:2499030] [MT] DTDeviceKit: deviceType from 4c575fb44229a557d91773f8091e98bed27bccb3 was NULL
    2020-09-22 17:37:13.830 xcodebuild[77636:2499030] [MT] DTDeviceKit: deviceType from 4c575fb44229a557d91773f8091e98bed27bccb3 was NULL
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/chul.kim/Local/flutter/forms/ios/Runner/AppDelegate.swift:12:63: error: missing argument for parameter 'completion' in call
        if let authResult = DBClientsManager.handleRedirectURL(url) {
                                                                  ^
                                                                  , completion: <#DBOAuthCompletion#>
    ObjectiveDropboxOfficial.DBClientsManager:13:21: note: 'handleRedirectURL(_:completion:)' declared here
        open class func handleRedirectURL(_ url: URL, completion: @escaping DBOAuthCompletion) -> Bool
                        ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Flutter' from project 'Pods')
Could not build the precompiled application for the device.
```

It seems that the `DBClientsManager.handleRedirectURL` method wants two arguments, not just `url` but also `completion`. Not knowing Swift at all, I have no idea how to provide this second argument. Can you please help?

**Comment by Viniciusbudel** [comment]
Same here

**Comment by hoanganhtran1010** [comment]
try this!

```
 override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        //        let oauthCompletion: DBOAuthCompletion()
        DBClientsManager.handleRedirectURL(url) {authResult in
            
        }
        return true
    }
```

**Comment by Viniciusbudel** [comment]
> try this!
> 
> ```
>  override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
>         //        let oauthCompletion: DBOAuthCompletion()
>         DBClientsManager.handleRedirectURL(url) {authResult in
>             
>         }
>         return true
>     }
> ```

I use this, the error is gone, but when i call any dropbox method 

Apllication crashs with this error in delegate

2021-02-17 11:05:10.297303-0300 Runner[420:68313] *** Assertion failure in +[DBClientsManager setupWithOAuthManager:transportConfig:], /ObjectiveDropboxOfficial/Source/ObjectiveDropboxOfficial/Shared/Handwritten/DBClientsManager.m:106
2021-02-17 11:05:10.301508-0300 Runner[420:68313] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only call `[DBClientsManager setupWith...]` once'
*** First throw call stack:
(0x1fe08b180 0x1fd2639f8 0x1fdfa488c 0x1fea68b38 0x103055298 0x1030542a4 0x10305413c 0x100ecb4cc 0x101929704 0x1010e8144 0x1013c1bd8 0x1010f1670 0x1010f3d7c 0x1fe01d554 0x1fe01d284 0x1fe01cab8 0x1fe017a08 0x1fe016fb4 0x20021879c 0x22a6bec38 0x100b8d10c 0x1fdada8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mix1009** [comment]
updated the documentation.
